# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

In [14]:
!pip install numpy
import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5]) 

print(my_arreglow)
print(np.mean(my_arreglow))


Defaulting to user installation because normal site-packages is not writeable
[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [1]:
# Solución (:

import numpy as np

array_ceros = np.zeros((3, 4))

print(array_ceros)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [2]:
# Solucion :)

import numpy as np

array = np.array([1, 2, 3, 4, 5])

suma = np.sum(array)

print("La suma da un total de:", suma)

La suma da un total de: 15


### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [3]:
array = np.array([10, 20, 30, 40, 50])

# Solución:)

import numpy as np

valor_maximo = np.max(array)

valor_minimo = np.min(array)

print("El valor máximo es:", valor_maximo)
print("El valor mínimo es:", valor_minimo)

El valor máximo es: 50
El valor mínimo es: 10


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [4]:
# Solución:)

import numpy as np

array = np.array([10, 20, 30, 40, 50])

valor_maximo = np.max(array)

valor_minimo = np.min(array)


print("El valor máximo es:", valor_maximo)
print("El valor mínimo es:", valor_minimo)

El valor máximo es: 50
El valor mínimo es: 10


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [5]:
# Solución:)

import numpy as np

array_aleatorio = np.random.rand(5)

print("Array números aleatorios:", array_aleatorio)

Array números aleatorios: [0.83999671 0.58886062 0.57267973 0.01919352 0.13464365]


### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [6]:
#Solucion:)

import numpy as np

array = np.array([5, 10, 15, 20, 25])

promedio = np.mean(array)

print("Promedio del array:", promedio)

Promedio del array: 15.0


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [7]:
#Solucion:)

import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

array_concatenado = np.concatenate((A, B))

print("Array concatenado:", array_concatenado)

Array concatenado: [1 2 3 4 5 6]


### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [8]:
#Solución:)

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

matriz = np.reshape(array, (2, 3))

print("Matriz 2x3:")
print(matriz)

Matriz 2x3:
[[1 2 3]
 [4 5 6]]


### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [9]:
#Solución:)

import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

producto_punto = np.dot(A, B)

print("El producto punto es:", producto_punto)

El producto punto es: 32


### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [11]:
#Solución:)

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

matriz = array.reshape(2, 5)

print("Matriz 2x5:")
print(matriz)


Matriz 2x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [ ]:
#Solucion :o
arr = np.array([9, 3, 6, 2, 1, 7])

import numpy as np

# Encontramos el 3 elemento más pequeño k=3
k = 3
k_esimo_menor = np.partition(arr, k-1)[k-1] # divide en dos partes sin ordenarlos


print(f"El {k}er elemento más pequeño es:", k_esimo_menor)

El 3er elemento más pequeño es: 3


## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [26]:
# Solucion del ROIROIROIROIORIORI


### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```

